/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.analysis;

import se.kth.badgers.lexparse.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTClass(TClass node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTReturn(TReturn node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTPrintln(TPrintln node);
    void caseTThis(TThis node);
    void caseTNew(TNew node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTString(TString node);
    void caseTInt(TInt node);
    void caseTBoolean(TBoolean node);
    void caseTNumber(TNumber node);
    void caseTTemp(TTemp node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTStar(TStar node);
    void caseTMod(TMod node);
    void caseTAnd(TAnd node);
    void caseTLessThan(TLessThan node);
    void caseTLogicalNot(TLogicalNot node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTDot(TDot node);
    void caseTComma(TComma node);
    void caseTSemiColon(TSemiColon node);
    void caseTAssign(TAssign node);
    void caseTBlank(TBlank node);
    void caseTStarComment(TStarComment node);
    void caseTLineComment(TLineComment node);
    void caseTIdentifier(TIdentifier node);
    void caseTIntLiteral(TIntLiteral node);
    void caseTLongLiteral(TLongLiteral node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
