/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class AAdditiveExprRestAdditiveExprRest extends PAdditiveExprRest
{
    private PPlusExpr _plusExpr_;

    public AAdditiveExprRestAdditiveExprRest()
    {
        // Constructor
    }

    public AAdditiveExprRestAdditiveExprRest(
        @SuppressWarnings("hiding") PPlusExpr _plusExpr_)
    {
        // Constructor
        setPlusExpr(_plusExpr_);

    }

    @Override
    public Object clone()
    {
        return new AAdditiveExprRestAdditiveExprRest(
            cloneNode(this._plusExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditiveExprRestAdditiveExprRest(this);
    }

    public PPlusExpr getPlusExpr()
    {
        return this._plusExpr_;
    }

    public void setPlusExpr(PPlusExpr node)
    {
        if(this._plusExpr_ != null)
        {
            this._plusExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusExpr_ == child)
        {
            this._plusExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusExpr_ == oldChild)
        {
            setPlusExpr((PPlusExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
