/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import java.util.*;
import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class AAndExprAndExpr extends PAndExpr
{
    private PLessThanExpr _lessThanExpr_;
    private final LinkedList<PAndExprRest> _andExprRest_ = new LinkedList<PAndExprRest>();

    public AAndExprAndExpr()
    {
        // Constructor
    }

    public AAndExprAndExpr(
        @SuppressWarnings("hiding") PLessThanExpr _lessThanExpr_,
        @SuppressWarnings("hiding") List<?> _andExprRest_)
    {
        // Constructor
        setLessThanExpr(_lessThanExpr_);

        setAndExprRest(_andExprRest_);

    }

    @Override
    public Object clone()
    {
        return new AAndExprAndExpr(
            cloneNode(this._lessThanExpr_),
            cloneList(this._andExprRest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExprAndExpr(this);
    }

    public PLessThanExpr getLessThanExpr()
    {
        return this._lessThanExpr_;
    }

    public void setLessThanExpr(PLessThanExpr node)
    {
        if(this._lessThanExpr_ != null)
        {
            this._lessThanExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThanExpr_ = node;
    }

    public LinkedList<PAndExprRest> getAndExprRest()
    {
        return this._andExprRest_;
    }

    public void setAndExprRest(List<?> list)
    {
        for(PAndExprRest e : this._andExprRest_)
        {
            e.parent(null);
        }
        this._andExprRest_.clear();

        for(Object obj_e : list)
        {
            PAndExprRest e = (PAndExprRest) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._andExprRest_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessThanExpr_)
            + toString(this._andExprRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessThanExpr_ == child)
        {
            this._lessThanExpr_ = null;
            return;
        }

        if(this._andExprRest_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lessThanExpr_ == oldChild)
        {
            setLessThanExpr((PLessThanExpr) newChild);
            return;
        }

        for(ListIterator<PAndExprRest> i = this._andExprRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAndExprRest) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
