/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class ALessThanExprRestLessThanExprRest extends PLessThanExprRest
{
    private TLessThan _lessThan_;
    private PAdditiveExpr _additiveExpr_;

    public ALessThanExprRestLessThanExprRest()
    {
        // Constructor
    }

    public ALessThanExprRestLessThanExprRest(
        @SuppressWarnings("hiding") TLessThan _lessThan_,
        @SuppressWarnings("hiding") PAdditiveExpr _additiveExpr_)
    {
        // Constructor
        setLessThan(_lessThan_);

        setAdditiveExpr(_additiveExpr_);

    }

    @Override
    public Object clone()
    {
        return new ALessThanExprRestLessThanExprRest(
            cloneNode(this._lessThan_),
            cloneNode(this._additiveExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessThanExprRestLessThanExprRest(this);
    }

    public TLessThan getLessThan()
    {
        return this._lessThan_;
    }

    public void setLessThan(TLessThan node)
    {
        if(this._lessThan_ != null)
        {
            this._lessThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThan_ = node;
    }

    public PAdditiveExpr getAdditiveExpr()
    {
        return this._additiveExpr_;
    }

    public void setAdditiveExpr(PAdditiveExpr node)
    {
        if(this._additiveExpr_ != null)
        {
            this._additiveExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._additiveExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessThan_)
            + toString(this._additiveExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessThan_ == child)
        {
            this._lessThan_ = null;
            return;
        }

        if(this._additiveExpr_ == child)
        {
            this._additiveExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lessThan_ == oldChild)
        {
            setLessThan((TLessThan) newChild);
            return;
        }

        if(this._additiveExpr_ == oldChild)
        {
            setAdditiveExpr((PAdditiveExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
