/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class AMinusExprMinusExpr extends PMinusExpr
{
    private TMinus _minus_;
    private PTimesExpr _timesExpr_;

    public AMinusExprMinusExpr()
    {
        // Constructor
    }

    public AMinusExprMinusExpr(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PTimesExpr _timesExpr_)
    {
        // Constructor
        setMinus(_minus_);

        setTimesExpr(_timesExpr_);

    }

    @Override
    public Object clone()
    {
        return new AMinusExprMinusExpr(
            cloneNode(this._minus_),
            cloneNode(this._timesExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusExprMinusExpr(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PTimesExpr getTimesExpr()
    {
        return this._timesExpr_;
    }

    public void setTimesExpr(PTimesExpr node)
    {
        if(this._timesExpr_ != null)
        {
            this._timesExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timesExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._timesExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._timesExpr_ == child)
        {
            this._timesExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._timesExpr_ == oldChild)
        {
            setTimesExpr((PTimesExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
