/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class APlusExprPlusExpr extends PPlusExpr
{
    private TPlus _plus_;
    private PTimesExpr _timesExpr_;

    public APlusExprPlusExpr()
    {
        // Constructor
    }

    public APlusExprPlusExpr(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PTimesExpr _timesExpr_)
    {
        // Constructor
        setPlus(_plus_);

        setTimesExpr(_timesExpr_);

    }

    @Override
    public Object clone()
    {
        return new APlusExprPlusExpr(
            cloneNode(this._plus_),
            cloneNode(this._timesExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExprPlusExpr(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PTimesExpr getTimesExpr()
    {
        return this._timesExpr_;
    }

    public void setTimesExpr(PTimesExpr node)
    {
        if(this._timesExpr_ != null)
        {
            this._timesExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timesExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._timesExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._timesExpr_ == child)
        {
            this._timesExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._timesExpr_ == oldChild)
        {
            setTimesExpr((PTimesExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
