/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import java.util.*;
import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class ASequenceArgList extends PArgList
{
    private final LinkedList<PArgListRest> _argListRest_ = new LinkedList<PArgListRest>();

    public ASequenceArgList()
    {
        // Constructor
    }

    public ASequenceArgList(
        @SuppressWarnings("hiding") List<?> _argListRest_)
    {
        // Constructor
        setArgListRest(_argListRest_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceArgList(
            cloneList(this._argListRest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceArgList(this);
    }

    public LinkedList<PArgListRest> getArgListRest()
    {
        return this._argListRest_;
    }

    public void setArgListRest(List<?> list)
    {
        for(PArgListRest e : this._argListRest_)
        {
            e.parent(null);
        }
        this._argListRest_.clear();

        for(Object obj_e : list)
        {
            PArgListRest e = (PArgListRest) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argListRest_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argListRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argListRest_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PArgListRest> i = this._argListRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgListRest) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
