/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import java.util.*;
import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class ASequenceExprList extends PExprList
{
    private PExpr _expr_;
    private final LinkedList<PExprRest> _exprRest_ = new LinkedList<PExprRest>();

    public ASequenceExprList()
    {
        // Constructor
    }

    public ASequenceExprList(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<?> _exprRest_)
    {
        // Constructor
        setExpr(_expr_);

        setExprRest(_exprRest_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceExprList(
            cloneNode(this._expr_),
            cloneList(this._exprRest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceExprList(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PExprRest> getExprRest()
    {
        return this._exprRest_;
    }

    public void setExprRest(List<?> list)
    {
        for(PExprRest e : this._exprRest_)
        {
            e.parent(null);
        }
        this._exprRest_.clear();

        for(Object obj_e : list)
        {
            PExprRest e = (PExprRest) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._exprRest_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._exprRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._exprRest_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PExprRest> i = this._exprRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExprRest) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
