/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.kth.badgers.lexparse.node;

import se.kth.badgers.lexparse.analysis.*;

@SuppressWarnings("nls")
public final class ATimesExprRestTimesExprRest extends PTimesExprRest
{
    private TStar _star_;
    private PPrefixExpr _prefixExpr_;

    public ATimesExprRestTimesExprRest()
    {
        // Constructor
    }

    public ATimesExprRestTimesExprRest(
        @SuppressWarnings("hiding") TStar _star_,
        @SuppressWarnings("hiding") PPrefixExpr _prefixExpr_)
    {
        // Constructor
        setStar(_star_);

        setPrefixExpr(_prefixExpr_);

    }

    @Override
    public Object clone()
    {
        return new ATimesExprRestTimesExprRest(
            cloneNode(this._star_),
            cloneNode(this._prefixExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimesExprRestTimesExprRest(this);
    }

    public TStar getStar()
    {
        return this._star_;
    }

    public void setStar(TStar node)
    {
        if(this._star_ != null)
        {
            this._star_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._star_ = node;
    }

    public PPrefixExpr getPrefixExpr()
    {
        return this._prefixExpr_;
    }

    public void setPrefixExpr(PPrefixExpr node)
    {
        if(this._prefixExpr_ != null)
        {
            this._prefixExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prefixExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._star_)
            + toString(this._prefixExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._star_ == child)
        {
            this._star_ = null;
            return;
        }

        if(this._prefixExpr_ == child)
        {
            this._prefixExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._star_ == oldChild)
        {
            setStar((TStar) newChild);
            return;
        }

        if(this._prefixExpr_ == oldChild)
        {
            setPrefixExpr((PPrefixExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
